
version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - my-django-data:/app/media
      - ./db.sqlite3:/app/db.sqlite3  # Mount the SQLite database file from the current directory
    environment:
      - DJANGO_DB_HOST=db

volumes:
  my-django-data:
