FROM jenkins/jenkins:2.414.3-jdk17

USER root

RUN apt-get update && apt-get install -y ca-certificates curl gnupg

# Install Docker CLI
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg
RUN echo \
 "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
 "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
   tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && apt-get install -y docker-ce-cli

# Install Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

# Install Google Cloud SDK
ENV CLOUDSDK_CORE_DISABLE_PROMPTS 1
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-453.0.0-linux-x86_64.tar.gz
RUN tar -xf google-cloud-sdk-453.0.0-linux-x86_64.tar.gz -C /opt/
RUN /opt/google-cloud-sdk/install.sh
RUN rm -rf google-cloud-sdk-453.0.0-linux-x86_64.tar.gz

RUN groupadd docker
RUN touch /var/run/docker.sock
RUN chmod 666 /var/run/docker.sock
RUN usermod -aG docker jenkins

USER jenkins



# FROM jenkins/jenkins:2.414.3-jdk17

# USER root

# RUN apt-get update && apt-get install -y ca-certificates curl gnupg

# # Install Docker CLI
# RUN install -m 0755 -d /etc/apt/keyrings
# RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
# RUN chmod a+r /etc/apt/keyrings/docker.gpg
# RUN echo \
#  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
#  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
#    tee /etc/apt/sources.list.d/docker.list > /dev/null
# RUN apt-get update && apt-get install -y docker-ce-cli

# # Install Docker Compose
# RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# RUN chmod +x /usr/local/bin/docker-compose

# RUN groupadd docker
# RUN touch /var/run/docker.sock
# RUN chmod 666 /var/run/docker.sock
# RUN usermod -aG docker jenkins

# # Downloading gcloud package
# RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-453.0.0-linux-x86_64.tar.gz
# RUN tar -xf google-cloud-cli-453.0.0-linux-x86_64.tar.gz
# RUN ./google-cloud-sdk/install.sh
# RUN rm -rf google-cloud-cli-453.0.0-linux-x86_64.tar.gz

# USER jenkins


# FROM jenkins/jenkins:lts-jdk17
# USER root

# RUN groupadd -g 997 docker
# RUN gpasswd -a jenkins docker

# RUN apt-get update && apt-get install -y python3 python3-pip

# RUN apt-get update && apt-get install -y docker.io
# RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose --insecure
# RUN chmod +x /usr/local/bin/docker-compose
# # Install Docker CLI
# RUN apt-get update && \
#     apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
#     curl -fsSL https://get.docker.com | sh && \
#     apt-get clean

# # Install Google Cloud SDK
# # RUN apt-get install -y google-cloud-sdk
# RUN apt-get update && apt-get install -y curl gnupg
# RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
# RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
# RUN apt-get update && apt-get install -y google-cloud-sdk
# # Make sure the 'jenkins' user can run Docker commands
# RUN usermod -aG docker jenkins
# EXPOSE 8080
# USER jenkins



# FROM jenkins/jenkins:lts-jdk17
# USER root


# RUN apt-get update && apt-get install -y docker.io docker-compose google-cloud-sdk

# EXPOSE 8080

# USER jenkins